import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '../../constants';

export const homeScreenStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.background,
	},
	mapContainer: {
		flex: 1,
	},
	locationLoadingOverlay: {
		position: 'absolute',
		top: SPACING.lg,
		left: SPACING.md,
		right: SPACING.md,
		alignItems: 'center',
	},
	showSpotsButton: {
		position: 'absolute',
		top: SPACING.xl + SPACING.md,
		right: SPACING.md,
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: SPACING.md,
		paddingVertical: SPACING.sm,
		borderRadius: SPACING.xl,
		backgroundColor: COLORS.primary,
		shadowColor: COLORS.text,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.15,
		shadowRadius: 6,
		elevation: 3,
	},
	showSpotsButtonPressed: {
		opacity: 0.85,
	},
	showSpotsButtonSpinner: {
		marginRight: SPACING.xs,
	},
	showSpotsButtonText: {
		color: COLORS.textLight,
		fontSize: 13,
		fontWeight: '700',
	},
	nonMapOverlay: {
		...StyleSheet.absoluteFillObject,
	},
	centerMarker: {
		position: 'absolute',
		left: '50%',
		top: '50%',
		marginLeft: -9,
		marginTop: -9,
		alignItems: 'center',
	},
	markerPin: {
		width: 18,
		height: 18,
		backgroundColor: COLORS.secondary,
		borderRadius: 12,
		borderWidth: 3,
		borderColor: COLORS.background,
	},
	compareDriverDirectionButton: {
		position: 'absolute',
		left: 16,
		backgroundColor: COLORS.surface,
		borderWidth: 1,
		borderColor: COLORS.border,
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
		paddingHorizontal: 14,
		paddingVertical: 10,
		shadowColor: COLORS.text,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.15,
		shadowRadius: 6,
		elevation: 3,
	},
	compareDriverDirectionButtonPressed: {
		opacity: 0.8,
	},
	compareDriverDirectionButtonText: {
		color: COLORS.text,
		fontSize: 13,
		fontWeight: '600',
	},
	markStopButton: {
		position: 'absolute',
		right: 16,
		backgroundColor: COLORS.warning,
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
		paddingHorizontal: 14,
		paddingVertical: 10,
		shadowColor: COLORS.text,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.15,
		shadowRadius: 6,
		elevation: 3,
	},
	markStopButtonPressed: {
		opacity: 0.85,
	},
	markStopButtonText: {
		color: COLORS.background,
		fontSize: 13,
		fontWeight: '700',
	},
});
